In [ ]:
!pip install pandasql
!pip install mysql-connector-python
!pip install boto3

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [5]:
import json
import pandas as pd
import mysql.connector

In [6]:
config = {}
class Extract:
  def start(self, name):
    self.name = name
    try:
      if '.json' in self.name:
        return self.__read_json()
      elif'.csv' in self.name:
        return self.__read_csv()
      else:
        print('Error en el formato permitido para el consumo de los archivos')
    except Error as e:
      print(e)

  def __read_csv(self):
    df = pd.read_csv(f'{self.name}')
    return df

  def __read_json(self):
    with open(f'{self.name}') as f:
      data = json.load(f)
    df = pd.json_normalize(data['datos'])
    return df

class Load:
  def __init__():
    pass
  
  def write_db():
    pass
  
  def write_report():
    pass

class Persistence:
  def __init__(self):
    self.cnx = mysql.connector.connect(**config)
    self.cursor = self.cnx.cursor()

  def get_tables(self):
    self.cursor.execute("SHOW TABLES")
    tables = [name_table[0] for name_table in list(self.cursor)]
    return tables

  def create_table(self, name_table):
    query = f"""CREATE TABLE IF NOT EXISTS TEST.`{name_table}` 
	                (fecha varchar(25), ruta varchar(10), 
                    ticket varchar(10), ocupacion double, 
                    src varchar(10), dst varchar(100), d_src double,
                    d_dst double, realizado boolean, estado varchar(10));"""
    self.cursor.execute(query)


  def insert_data(self, values, table_name):
    query = (f"""INSERT INTO `{table_name}` (fecha,ruta,ticket,ocupacion,src,dst,d_src,d_dst,realizado,estado) 
                     VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s);""")
    val = values
    self.cursor.executemany(query, val)
    self.cnx.commit()
    return self.cursor.rowcount


  def close(self):
    self.cursor.close()
    self.cnx.close()


class Service:
  def __init__(self, db, ext):
    self.db = db
    self.ext = ext
  def start_process(self):
    names = ['tickets_2020-01.csv', 'tickets_2020-01-01_api.json', 'tickets_2020-01-01_pp.json']
    for name in names:
      tables = self.db.get_tables()
      if (self.__validate_table(tables, name)):
        data = self.ext.start(name)
        columns = tuple(data.columns)
        values = [tuple(row) for row in data.values.tolist()]
        self.db.insert_data(values, name)
        print(f'Archivo {name}, terminado')
    self.db.close()
    print('Proceso terminado')

  def __validate_table(self, tables, name):
    if name in tables:
      """TODO EN CASO DE REQUERIR CALCULAR EL DELTA DE LOS NUEVOS DATOS ESTAR√çAN
      EN ESTA PARTE"""
      return True
    else:
      db.create_table(name)
      return True
  
  def get_names_files(self):
    pass

In [ ]:
db = Persistence()
ext = Extract()
Service(db, ext).start_process()

In [ ]:
names = ['tickets_2020_api.json', 'tickets_2020-01.csv', 'tickets_pp.json']
df = Extract().start(names[1])
df

In [ ]:
from pandasql import sqldf

In [ ]:
pysqldf = lambda q: sqldf(q, globals())

In [ ]:
sqldf(Q6, locals())

In [ ]:
Q1 = """SELECT COUNT(DISTINCT(ruta)) FROM nycphil"""

Q2 = """SELECT COUNT(ticket) FROM nycphil"""

Q3 = """SELECT DISTINCT(estado) FROM nycphil"""

Q4 = """SELECT DISTINCT(realizado) FROM nycphil"""

Q5 = """SELECT ruta, COUNT(*) FROM nycphil GROUP BY ruta ORDER BY COUNT(*) DESC"""

Q6 = """SELECT AVG(OCUPACION)*100 AS PROMEDIO  FROM nycphil """